<?php
/**
 * Valdecode
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category    Valdecode
 * @package     Valdecode_CookieLaw
 * @copyright   Copyright (c) 2013 Valdecode
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if (Mage::getStoreConfig('cookielaw/cookielaw/enabled')): ?>
    <div id="v-cookielaw" class="<?php echo Mage::getStoreConfig('cookielaw/cookielaw/position') ?> <?php echo Mage::getStoreConfig('cookielaw/cookielaw/skin') ?>" style="display: none">
        <div class="v-message">
            <?php $link = '<a href="'.Mage::getStoreConfig('cookielaw/cookielaw/cms_page').'">'.$this->__("cookie policy").'</a>' ?>
            <?php echo $this->__('This websites use cookies. By continuing to browse the site you are agreeing to our use of cookies. For more details about cookies and how to manage them, see our %s.', $link) ?>
        </div>
        <a href="javascript:cookieLaw.cookieLawAccept(<?php echo Mage::getStoreConfig('cookielaw/cookielaw/behaviour') ?>);" class="v-close"><?php echo $this->__("Accept") ?></a>
    </div>
    <script type="text/javascript">
        if (!cookieLaw.getCookie('cookielaw')) {
            document.getElementById('v-cookielaw').style.display = 'block';
        }
    </script>
<?php endif; ?>
